---
- name: create ~/repos/ directory
  file: path=~/repos/ state=directory

- name: git clone cosy-docker-layer
  git: repo=https://github.com/UCL-CATL/cosy-docker-layer.git
       dest=~/repos/cosy-docker-layer

- name: git clone docker-pupil
  git: repo=https://github.com/UCL-CATL/docker-pupil.git
       dest=~/repos/docker-pupil

- name: git clone cosy-pupil-server
  git: repo=https://github.com/UCL-CATL/cosy-pupil-server.git
       dest=~/repos/cosy-pupil-server

- name: git clone cosy-camera-recorder
  git: repo=https://github.com/UCL-CATL/cosy-camera-recorder.git
       dest=~/repos/cosy-camera-recorder

- name: git clone cosy-zeromq-matlab
  git: repo=https://github.com/UCL-CATL/cosy-zeromq-matlab.git
       dest=~/repos/cosy-zeromq-matlab

- name: git clone cosy-pupil-client
  git: repo=https://github.com/UCL-CATL/cosy-pupil-client.git
       dest=~/repos/cosy-pupil-client

- name: git clone cosy-pupil-install
  git: repo=https://github.com/UCL-CATL/cosy-pupil-install.git
       dest=~/repos/cosy-pupil-install
